# Site settings
title: "Mohamed youssef chlendi resume"
description: "Mohamed youssef chlendi full resume using github and github pages."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "FullStack developer"
resume_title:                   "INFORMATION SYSTEMS
DEVELOPMENT STUDENT"
resume_contact_email:           "youssef.chlendi@gmail.com"
resume_contact_telephone:       "22079448"
resume_contact_address:         "Zarzis, Medenine"
resume_header_contact_info: "Zarzis, Medenine | 22079448 | youssef.chlendi@gmail.com"
resume_header_intro: "<p>Charting the knowledge of the Internet, just like Galileo charted the stars.</p>"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/youssefchlendi/merge-conflicts"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/youssef.chlendi"
  resume_linkedin_url:          "https://www.linkedin.com/in/mohamed-youssef-chlendi-1b5624183/"
  resume_instagram_url:         "https://www.instagram.com/youssef.chlendi/"
  resume_website_url:           "https://youssefchlendi.github.io/merge-conflicts/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
